network:
  host: _site_
node:
  name: ${HOSTNAME}
index:
  number_of_replicas: 0
http:
  max_content_length: 500mb
cluster:
  routing:
    allocation:
      cluster_concurrent_rebalance: 2
    balance:
      primary: 1
marvel:
  agent:
    enabled: false
bootstrap:
  mlockall: true
indices:
  fielddata:
    cache:
      size: 25%
discovery:
  zen:
    ping:
      unicast:
        hosts: ["elastic1", "elastic2"]
      multicast:
        enabled: false
repositories:
  url:
    allowed_urls: ["https://elasticsearch-sample-data.s3.amazonaws.com/*"]
