network:
  host: _site_
node:
  name: ${ES_NODENAME}
index:
  number_of_replicas: 0
http:
  max_content_length: 500mb
cluster:
  routing:
    allocation:
      cluster_concurrent_rebalance: 2
    balance:
      primary: 1
bootstrap:
  mlockall: true
indices:
  fielddata:
    cache:
      size: 25%
discovery:
  zen:
    ping:
      unicast:
        hosts:
          - elastic1
      multicast:
        enabled: false
    minimum_master_nodes: 2
repositories:
  url:
    allowed_urls: ["https://elasticsearch-sample-data.s3.amazonaws.com/*"]
script:
  engine:
    groovy:
      inline:
        aggs: true
        mapping: true
        search: true
        update: true
        plugin: true
      indexed:
        aggs: true
        mapping: true
        search: true
        update: true
        plugin: true
