network:
  host: _site_
node:
  name: ${ES_NODENAME}
http:
  max_content_length: 500mb
cluster:
  routing:
    allocation:
      cluster_concurrent_rebalance: 2
bootstrap:
  memory_lock: true
indices:
  fielddata:
    cache:
      size: 25%
discovery:
  zen:
    ping:
      unicast:
        hosts:
          - elastic1
    minimum_master_nodes: 2
repositories:
  url:
    allowed_urls: ["https://elasticsearch-sample-data.s3.amazonaws.com/*"]
script:
  engine:
    groovy:
      inline:
        aggs: true
        search: true
        update: true
xpack.security.authc:
  anonymous:
    roles: superuser, kibana_user
    authz_exception: false
