version: '2'
services:
  elastic1:
    extends:
      file: docker-compose-elasticsearch.yml
      service: elasticsearch
    environment:
      ES_NODENAME: elastic1
    ports:
      - "9200:9200"
      - "9300:9300"
  elastic2:
    extends:
      file: docker-compose-elasticsearch.yml
      service: elasticsearch
    environment:
      ES_NODENAME: elastic2
    ports:
      - "9201:9200"
      - "9301:9300"
  elastic3:
    extends:
      file: docker-compose-elasticsearch.yml
      service: elasticsearch
    environment:
      ES_NODENAME: elastic3
    ports:
      - "9202:9200"
      - "9302:9300"
  inquisitor:
    image: spantree/elasticsearch-inquisitor
    environment:
      ELASTICSEARCH_URL: "http://elastic1:9200"
    ports:
      - "9400:80"
  # www:
  #   image: spantree/elasticsearch-talk-www:latest
  #   ports:
  #     - "80:80"
  # logstash:
  #   image: spantree/logstash-star-wars-kid:latest
  #   ports:
  #     - "3333:3333"
  #     - "9201:9200"
  #   environment:
  #     ES_HEAP_SIZE: 2g
  #   command: "logstash agent --config /etc/logstash/conf.d/logstash.conf"
  kibana:
    build: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elastic1:9200"
    depends_on:
      - elastic1
      - elastic2
  slides:
    image: spantree/reveal:3.4.0
    ports:
      - "9000:9000"
      # live reload port
      - "35729:35729"
    volumes:
      - ./slides:/usr/src/slides
      - /usr/src/slides/node_modules
      - /usr/src/slides/bower_components
