# Use this config only if you want to build all the Docker images
# locally (this could take quite some time)
elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
www:
  build: www
  ports:
    - "80:80"
logstash:
  build: logstash
  ports:
    - "9201:9200"
    - "3333:3333"
kibana:
  image: digitalwonderland/kibana:latest