version: '2'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
      - "./elasticsearch/config/analysis:/usr/share/elasticsearch/config/analysis"
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    environment:
      ES_NODENAME: $HOSTNAME
    ulimits:
      memlock:
        soft: -1
        hard: -1
