version: '2'
services:
  elastic1:
    build: elasticsearch
    volumes:
      - "./elasticsearch/config:/usr/share/elasticsearch/config"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  elastic2:
    build: elasticsearch
    volumes:
      - "./elasticsearch/config:/usr/share/elasticsearch/config"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
      - "9301:9300"
  # www:
  #   image: spantree/elasticsearch-talk-www:latest
  #   ports:
  #     - "80:80"
  # logstash:
  #   image: spantree/logstash-star-wars-kid:latest
  #   ports:
  #     - "3333:3333"
  #     - "9201:9200"
  #   environment:
  #     ES_HEAP_SIZE: 2g
  #   command: "logstash agent --config /etc/logstash/conf.d/logstash.conf"
  # kibana:
  #   image: bobrik/kibana:4.0.2
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     KIBANA_ES_URL: "http://logstash:9200"
  slides:
    image: spantree/reveal:3.4.0
    ports:
      - "9000:9000"
    volumes:
      - ./slides:/usr/src/slides
      - /usr/src/slides/node_modules
      - /usr/src/slides/bower_components
