# Use this config if you only want to view the API examples and sldies

elasticsearch:
  image: spantree/elasticsearch-talk-es:latest
  ports:
    - "9200:9200"
    - "9300:9300"
www:
  image: spantree/elasticsearch-talk-www:latest
  ports:
    - "80:80"